version: "3"

services:
  app:
    build: .
    container_name: micro-codeflix-app
    command: .docker/start.sh
    volumes:
      - .:/home/node/app
    ports:
      - 3000:3000
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  keycloak:
    image: jboss/keycloak:16.1.1
    container_name: micro-codeflix-keycloak
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=h2
    volumes:
      - ./.docker/keycloak:/opt/jboss/keycloak/standalone/data
    ports:
      - 8181:8080
